#include "gui_crap.h"
void IHateGTK::GetItemImages()
{
		item_images.insert({"KnifeChitin", "/items/Abyssal_razor.png"});//1
		item_images.insert({"piece_workbench_ext3", "/items/Adze.png"});//1
		item_images.insert({"Amber", "/items/Amber.png"});//20
		item_images.insert({"AmberPearl", "/items/Amber_pearl.png"});//50
		item_images.insert({"AncientSeed", "/items/Ancient_seed.png"});//50
		item_images.insert({"PickaxeAntler", "/items/Antler_pickaxe.png"});//1
		item_images.insert({"forge_ext2", "/items/Anvils.png"});//1
		item_images.insert({"ElderBark", "/items/Ancient_bark.png"});//50
		item_images.insert({"SpearElderbark", "/items/Ancient_bark_spear.png"});//1
		item_images.insert({"ShieldBanded", "/items/Shield_banded0.png"});//1
		item_images.insert({"Barley", "/items/Barley.png"});//100
		item_images.insert({"BarleyFlour", "/items/Barley_flour.png"});//20
		item_images.insert({"bed", "/items/Bed.png"});//1
		item_images.insert({"BeechSeeds", "/items/Beech_seeds.png"});//100
		item_images.insert({"BlackMetal", "/items/Black_metal.png"});//30
		item_images.insert({"BlackMetalScrap", "/items/Black_metal_scrap.png"});//30
		item_images.insert({"ShieldBlackmetal", "/items/Black_metal_shield.png"});//1
		item_images.insert({"ShieldBlackmetalTower", "/items/Black_metal_tower_shield.png"});//1
		item_images.insert({"AtgeirBlackmetal", "/items/Blackmetal_atgeir.png"});//1
		item_images.insert({"AxeBlackMetal", "/items/Blackmetal_axe.png"});//1
		item_images.insert({"KnifeBlackMetal", "/items/Blackmetal_knife.png"});//1
		item_images.insert({"SwordBlackmetal", "/items/Blackmetal_sword.png"});//1
		item_images.insert({"TrophyBlob", "/items/Blob_trophy.png"});//20
		item_images.insert({"Bloodbag", "/items/Bloodbag.png"});//50
		item_images.insert({"BloodPudding", "/items/Blood_pudding.png"});//10
		item_images.insert({"Blueberries", "/items/Blueberries.png"});//50
		item_images.insert({"TrophyBoar", "/items/Boar_trophy.png"});//20
		item_images.insert({"BoneFragments", "/items/Bone_fragments.png"});//50
		item_images.insert({"TrophyBonemass", "/items/Bonemass_trophy.png"});//20
		item_images.insert({"bonfire", "/items/Bonfire.png"});//1
		item_images.insert({"Bread", "/items/Bread.png"});//20
		item_images.insert({"Bronze", "/items/Bronze.png"});//30
		item_images.insert({"AtgeirBronze", "/items/Bronze_atgeir.png"});//1
		item_images.insert({"AxeBronze", "/items/Bronze_axe.png"});//1
		item_images.insert({"ShieldBronzeBuckler", "/items/Bronze_buckler.png"});//1
		item_images.insert({"HelmetBronze", "/items/Bronze_helmet.png"});//1
		item_images.insert({"MaceBronze", "/items/Bronze_mace.png"});//1
		item_images.insert({"BronzeNails", "/items/Bronze_nails.png"});//100
		item_images.insert({"PickaxeBronze", "/items/Bronze_pickaxe.png"});//1
		item_images.insert({"ArmorBronzeChest", "/items/Bronze_plate_cuirass.png"});//1
		item_images.insert({"ArmorBronzeLegs", "/items/Bronze_plate_leggings.png"});//1
		item_images.insert({"SpearBronze", "/items/Bronze_spear.png"});//1
		item_images.insert({"SwordBronze", "/items/Bronze_sword.png"});//1
		item_images.insert({"ArrowBronze", "/items/Bronzehead_arrow.png"});//1
		item_images.insert({"fire_pit", "/items/Campfire.png"});//1
		item_images.insert({"CapeOdin", "/items/Cape_of_Odin.png"});//1
		item_images.insert({"Carrot", "/items/Carrot.png"});//50
		item_images.insert({"CarrotSeeds", "/items/Carrot_seeds.png"});//100
		item_images.insert({"CarrotSoup", "/items/Carrot_soup.png"});//10
		item_images.insert({"Cart", "/items/Cart.png"});//1
		item_images.insert({"Chain", "/items/Chain.png"});//50
		item_images.insert({"charcoal_kiln", "/items/Charcoal_kiln.png"});//1
		item_images.insert({"Chitin", "/items/Chitin.png"});//50
		item_images.insert({"piece_workbench_ext1", "/items/Chopping_block.png"});//1
		item_images.insert({"Cloudberry", "/items/Cloudberries.png"});//50
		item_images.insert({"Club", "/items/Club.png"});//1
		item_images.insert({"Coal", "/items/Coal.png"});//50
		item_images.insert({"Coins", "/items/Coins.png"});//999
		item_images.insert({"FishCooked", "/items/Cooked_fish.png"});//20
		item_images.insert({"CookedLoxMeat", "/items/Cooked_lox_meat.png"});//20
		item_images.insert({"CookedMeat", "/items/Cooked_meat.png"});//20
		item_images.insert({"SerpentMeatCooked", "/items/Cooked_serpent_meat.png"});//50
		item_images.insert({"piece_cookingstation", "/items/Cooking_station.png"});//1
		item_images.insert({"Copper", "/items/Copper.png"});//30
		item_images.insert({"KnifeCopper", "/items/Copper_knife.png"});//1
		item_images.insert({"CopperOre", "/items/Copper_ore.png"});//30
		item_images.insert({"RoundLog", "/items/Core_wood.png"});//50
		item_images.insert({"Bow", "/items/Crude_bow.png"});//1
		item_images.insert({"Crystal", "/items/Crystal.png"});//50
		item_images.insert({"Cultivator", "/items/Cultivator.png"});//1
		item_images.insert({"Dandelion", "/items/Dandelion.png"});//50
		item_images.insert({"TrophyDeathsquito", "/items/Deathsquito_trophy.png"});//20
		item_images.insert({"DeerHide", "/items/Deer_hide.png"});//50
		item_images.insert({"CapeDeerHide", "/items/Deer_hide_cape.png"});//1
		item_images.insert({"rug_deer", "/items/Deer_rug.png"});//1
		item_images.insert({"TrophyDeer", "/items/Deer_trophy.png"});//20
		item_images.insert({"HelmetDrake", "/items/Drake_helmet.png"});//1
		item_images.insert({"TrophyHatchling", "/items/Drake_trophy.png"});//20
		item_images.insert({"TrophyDraugrElite", "/items/Draugr_Elite_trophy.png"});//20
		item_images.insert({"TrophyDraugr, TrophyDraugrFem", "/items/Draugr_trophy.png"});//20
		item_images.insert({"DragonEgg", "/items/Dragon_egg.png"});//1
		item_images.insert({"piece_bed02", "/items/Dragon_bed.png"});//1
		item_images.insert({"DragonTear", "/items/Dragon_tear.png"});//50
		item_images.insert({"HelmetDverger", "/items/Dverger_circlet.png"});//1
		item_images.insert({"TrophyEikthyr", "/items/Eikthyr_trophy.png"});//20
		item_images.insert({"TrophyTheElder", "/items/The_Elder_trophy.png"});//20
		item_images.insert({"Entrails", "/items/Entrails.png"});//50
		item_images.insert({"SpearWolfFang", "/items/Fang_spear.png"});//1
		item_images.insert({"TrophyFenring", "/items/Fenring_trophy.png"});//20
		item_images.insert({"fermenter", "/items/Fermenter.png"});//1
		item_images.insert({"FineWood", "/items/Fine_wood.png"});//50
		item_images.insert({"BowFineWood", "/items/Finewood_bow.png"});//1
		item_images.insert({"FirCone", "/items/Fir_cone.png"});//100
		item_images.insert({"Fish1, Fish2, Fish3, Fish4_cave", "/items/Pike.png"});//1
		item_images.insert({"FishingRod", "/items/Fishing_rod.png"});//1
		item_images.insert({"ArrowFire", "/items/Fire_arrow.png"});//1
		item_images.insert({"BarleyWine", "/items/Fire_resistance_barley_wine.png"});//10
		item_images.insert({"FishWraps", "/items/Fish_wraps.png"});//10
		item_images.insert({"Flax", "/items/Flax.png"});//100
		item_images.insert({"Flint", "/items/Flint.png"});//30
		item_images.insert({"AxeFlint", "/items/Flint_axe.png"});//1
		item_images.insert({"ArrowFlint", "/items/Flinthead_arrow.png"});//1
		item_images.insert({"KnifeFlint", "/items/Flint_knife.png"});//1
		item_images.insert({"SpearFlint", "/items/Flint_spear.png"});//1
		item_images.insert({"piece_forge", "/items/Forge.png"});//1
		item_images.insert({"forge_ext1", "/items/Forge_bellows.png"});//1
		item_images.insert({"forge_ext5", "/items/Forge_cooler.png"});//1
		item_images.insert({"forge_ext6", "/items/Forge_toolrack.png"});//1
		item_images.insert({"FreezeGland", "/items/Freeze_gland.png"});//50
		item_images.insert({"MeadFrostResist", "/items/Frost_resist_mead.png"});//10
		item_images.insert({"MaceSilver", "/items/Frostner.png"});//1
		item_images.insert({"TrophyGoblinBrute", "/items/Fuling_berserker_trophy.png"});//20
		item_images.insert({"TrophyGoblinShaman", "/items/Fuling_shaman_trophy.png"});//20
		item_images.insert({"TrophyGoblin", "/items/Fuling_trophy.png"});//20
		item_images.insert({"GreydwarfEye", "/items/Greydwarf_eye.png"});//50
		item_images.insert({"TrophyGreydwarfBrute", "/items/Greydwarf_Brute_trophy.png"});//20
		item_images.insert({"TrophyGreydwarfShaman", "/items/Greydwarf_Shaman_trophy.png"});//20
		item_images.insert({"TrophyGreydwarf", "/items/Greydwarf_trophy.png"});//20
		item_images.insert({"NeckTailGrilled", "/items/Grilled_neck_tail.png"});//20
		item_images.insert({"forge_ext3", "/items/Grinding_wheel.png"});//1
		item_images.insert({"Guck", "/items/Guck.png"});//50
		item_images.insert({"HardAntler", "/items/Hard_antler.png"});//50
		item_images.insert({"Hammer", "/items/Hammer.png"});//1
		item_images.insert({"Hoe", "/items/Hoe.png"});//1
		item_images.insert({"Honey", "/items/Honey.png"});//50
		item_images.insert({"HelmetOdin", "/items/Hood_of_Odin.png"});//1
		item_images.insert({"Iron", "/items/Iron.png"});//30
		item_images.insert({"AtgeirIron", "/items/Iron_atgeir.png"});//1
		item_images.insert({"AxeIron", "/items/Iron_axe.png"});//1
		item_images.insert({"ArmorIronLegs", "/items/Iron_greaves.png"});//1
		item_images.insert({"HelmetIron", "/items/Iron_helmet.png"});//1
		item_images.insert({"MaceIron", "/items/Iron_mace.png"});//1
		item_images.insert({"IronNails", "/items/Iron_nails.png"});//100
		item_images.insert({"PickaxeIron", "/items/Iron_pickaxe.png"});//1
		item_images.insert({"ArmorIronChest", "/items/Iron_scale_mail.png"});//1
		item_images.insert({"SledgeIron", "/items/Iron_sledge.png"});//1
		item_images.insert({"SwordIron", "/items/Iron_sword.png"});//1
		item_images.insert({"ShieldIronTower", "/items/Iron_tower_shield.png"});//1
		item_images.insert({"ArrowIron", "/items/Ironhead_arrow.png"});//1
		item_images.insert({"Karve", "/items/Karve.png"});//1
		item_images.insert({"HelmetLeather", "/items/Leather_helmet.png"});//1
		item_images.insert({"ArmorLeatherLegs", "/items/Leather_pants.png"});//1
		item_images.insert({"LeatherScraps", "/items/Leather_scraps.png"});//50
		item_images.insert({"TrophyLeech", "/items/Leech_trophy.png"});//20
		item_images.insert({"CapeLinen", "/items/Linen_cape.png"});//1
		item_images.insert({"ArmorLeatherChest", "/items/Leather_tunic.png"});//1
		item_images.insert({"LinenThread", "/items/Linen_thread.png"});//50
		item_images.insert({"VikingShip", "/items/Longship.png"});//1
		item_images.insert({"CapeLox", "/items/Lox_cape.png"});//1
		item_images.insert({"LoxMeat", "/items/Lox_meat.png"});//20
		item_images.insert({"LoxPie", "/items/Lox_meat_pie.png"});//10
		item_images.insert({"LoxPelt", "/items/Lox_pelt.png"});//50
		item_images.insert({"rug_fur", "/items/Lox_rug.png"});//1
		item_images.insert({"TrophyLox", "/items/Lox_trophy.png"});//20
		item_images.insert({"TankardOdin", "/items/Mead_horn_of_Odin.png"});//1
		item_images.insert({"MeadHealthMedium", "/items/Medium_healing_mead.png"});//10
		item_images.insert({"MeadStaminaMedium", "/items/Medium_stamina_mead.png"});//10
		item_images.insert({"BeltStrength", "/items/Megingjord.png"});//1
		item_images.insert({"MeadHealthMinor", "/items/Minor_healing_mead.png"});//10
		item_images.insert({"MeadStaminaMinor", "/items/Minor_stamina_mead.png"});//10
		item_images.insert({"TrophyDragonQueen", "/items/Moder_trophy.png"});//20
		item_images.insert({"Mushroom", "/items/Mushroom.png"});//50
		item_images.insert({"NeckTail", "/items/Neck_tail.png"});//50
		item_images.insert({"TrophyNeck", "/items/Neck_trophy.png"});//20
		item_images.insert({"Needle", "/items/Needle.png"});//50
		item_images.insert({"Obsidian", "/items/Obsidian.png"});//50
		item_images.insert({"ArrowObsidian", "/items/Obsidian_arrow.png"});//1
		item_images.insert({"Ooze", "/items/Ooze.png"});//50
		item_images.insert({"BombOoze", "/items/Ooze_bomb.png"});//1
		item_images.insert({"ArmorPaddedCuirass", "/items/Padded_cuirass.png"});//1
		item_images.insert({"ArmorPaddedGreaves", "/items/Padded_greaves.png"});//1
		item_images.insert({"HelmetPadded", "/items/Padded_helmet.png"});//1
		item_images.insert({"PineCone", "/items/Pine_cone.png"});//100
		item_images.insert({"ArrowPoison", "/items/Poison_arrow.png"});//1
		item_images.insert({"MeadPoisonResist", "/items/Poison_resistance_mead.png"});//10
		item_images.insert({"portal_wood", "/items/Portal.png"});//1
		item_images.insert({"MaceNeedle", "/items/Porcupine.png"});//1
		item_images.insert({"QueenBee", "/items/Queen_bee.png"});//20
		item_images.insert({"QueensJam", "/items/Queens_jam.png"});//10
		item_images.insert({"Raft", "/items/Raft.png"});//1
		item_images.insert({"ArmorRagsLegs", "/items/Rag_pants.png"});//1
		item_images.insert({"ArmorRagsChest", "/items/Rag_tunic.png"});//1
		item_images.insert({"TrophySkeletonPoison", "/items/Rancid_Remains_trophy.png"});//20
		item_images.insert({"Raspberry", "/items/Raspberries.png"});//50
		item_images.insert({"FishRaw", "/items/Raw_fish.png"});//20
		item_images.insert({"RawMeat", "/items/Raw_meat.png"});//20
		item_images.insert({"Resin", "/items/Resin.png"});//50
		item_images.insert({"Ruby", "/items/Ruby.png"});//20
		item_images.insert({"Sausages", "/items/Sausages.png"});//20
		item_images.insert({"piece_walltorch", "/items/Sconce.png"});//1
		item_images.insert({"SerpentMeat", "/items/Serpent_meat.png"});//50
		item_images.insert({"SerpentScale", "/items/Serpent_scale.png"});//50
		item_images.insert({"ShieldSerpentscale", "/items/Serpent_scale_shield.png"});//1
		item_images.insert({"SerpentStew", "/items/Serpent_stew.png"});//10
		item_images.insert({"TrophySerpent", "/items/Serpent_trophy.png"});//20
		item_images.insert({"SharpeningStone", "/items/Sharpening_stone.png"});//20
		item_images.insert({"sign", "/items/Sign.png"});//1
		item_images.insert({"SilverNecklace", "/items/Silver_necklace.png"});//20
		item_images.insert({"ShieldSilver", "/items/Silver_shield.png"});//1
		item_images.insert({"SwordSilver", "/items/Silver_sword.png"});//1
		item_images.insert({"TrophySkeleton", "/items/Skeleton_trophy.png"});//20
		item_images.insert({"forge_ext4", "/items/Smith%27s_anvil.png"});//1
		item_images.insert({"SledgeStagbreaker", "/items/Stagbreaker.png"});//1
		item_images.insert({"piece_groundtorch_green", "/items/Standing_green-burning_iron_torch.png"});//1
		item_images.insert({"piece_groundtorch", "/items/Standing_iron_torch.png"});//1
		item_images.insert({"piece_groundtorch_wood", "/items/Standing_wood_torch.png"});//1
		item_images.insert({"Stone", "/items/Stone.png"});//50
		item_images.insert({"piece_stonecutter", "/items/Stonecutter.png"});//1
		item_images.insert({"AxeStone", "/items/Stone_axe.png"});//1
		item_images.insert({"TrophySGolem", "/items/Stone_Golem_trophy.png"});//20
		item_images.insert({"stone_pile", "/items/Stone_pile.png"});//1
		item_images.insert({"SurtlingCore", "/items/Surtling_core.png"});//10
		item_images.insert({"TrophySurtling", "/items/Surtling_trophy.png"});//20
		item_images.insert({"Tankard", "/items/Tankard.png"});//1
		item_images.insert({"piece_workbench_ext2", "/items/Tanning_rack.png"});//1
		item_images.insert({"MeadTasty", "/items/Tasty_mead.png"});//10
		item_images.insert({"Thistle", "/items/Thistle.png"});//50
		item_images.insert({"Tin", "/items/Tin.png"});//30
		item_images.insert({"TinOre", "/items/Tin_ore.png"});//30
		item_images.insert({"Torch", "/items/Torch.png"});//1
		item_images.insert({"TrollHide", "/items/Troll_hide.png"});//20
		item_images.insert({"CapeTrollHide", "/items/Troll_hide_cape.png"});//1
		item_images.insert({"HelmetTrollLeather", "/items/Troll_leather_helmet.png"});//1
		item_images.insert({"ArmorTrollLeatherLegs", "/items/Troll_leather_pants.png"});//1
		item_images.insert({"ArmorTrollLeatherChest", "/items/Troll_leather_tunic.png"});//1
		item_images.insert({"TrophyForestTroll", "/items/Troll_trophy.png"});//20
		item_images.insert({"Turnip", "/items/Turnip.png"});//50
		item_images.insert({"TurnipSeeds", "/items/Turnip_seeds.png"});//100
		item_images.insert({"TurnipStew", "/items/Turnip_stew.png"});//10
		item_images.insert({"guard_stone", "/items/Ward.png"});//1
		item_images.insert({"windmill", "/items/Windmill.png"});//1
		item_images.insert({"Wishbone", "/items/Wishbone.png"});//1
		item_images.insert({"WitheredBone", "/items/Withered_bone.png"});//30
		item_images.insert({"ArmorWolfChest", "/items/Wolf_armor_chest.png"});//1
		item_images.insert({"ArmorWolfLegs", "/items/Wolf_armor_legs.png"});//1
		item_images.insert({"WolfFang", "/items/Wolf_fang.png"});//50
		item_images.insert({"CapeWolf", "/items/Wolf_fur_cape.png"});//1
		item_images.insert({"WolfPelt", "/items/Wolf_pelt.png"});//50
		item_images.insert({"TrophyWolf", "/items/Wolf_trophy.png"});//20
		item_images.insert({"Wood", "/items/Wood.png"});//50
		item_images.insert({"ArrowWood", "/items/Wood_arrow.png"});//1
		item_images.insert({"ShieldWood", "/items/Wood_shield.png"});//1
		item_images.insert({"ShieldWoodTower", "/items/Wood_tower_shield.png"});//1
		item_images.insert({"piece_workbench", "/items/Workbench.png"});//1
		item_images.insert({"TrophyWraith", "/items/Wraith_trophy.png"});//20
		item_images.insert({"TrophyGoblinKing", "/items/Yagluth_trophy.png"});//20
		item_images.insert({"MushroomYellow", "/items/Yellow_mushroom.png"});//50
		item_images.insert({"YmirRemains", "/items/Ymir_flesh.png"});//50
		item_images.insert({"HelmetYule", "/items/Yule_hat.png"});//1
};
